-- Table `card`
CREATE TABLE IF NOT EXISTS `card`
(
    `card_id`          bigint       NOT NULL AUTO_INCREMENT,
    `api_card_id`      varchar(255) NOT NULL,
    `artist`           varchar(255) DEFAULT NULL,
    `french_image_url` varchar(255) DEFAULT NULL,
    `french_name`      varchar(255) DEFAULT NULL,
    `image_url`        varchar(255) DEFAULT NULL,
    `mana_cost`        int          NOT NULL,
    `name`             varchar(255) DEFAULT NULL,
    `rarity`           varchar(255) DEFAULT NULL,
    `set_abbreviation` varchar(255) DEFAULT NULL,
    `set_name`         varchar(255) DEFAULT NULL,
    `text`             longtext,
    PRIMARY KEY (`card_id`),
    UNIQUE KEY `UK_89p3df3sgxl3e2h9nwqn128sd` (`api_card_id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;

-- Table `card_language`
CREATE TABLE IF NOT EXISTS `card_language`
(
    `card_language_id` bigint       NOT NULL AUTO_INCREMENT,
    `name`             varchar(255) NOT NULL,
    PRIMARY KEY (`card_language_id`),
    UNIQUE KEY `UK_aqshuw525u9c50e90kq02ob0v` (`name`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;

-- Table `card_quality`
CREATE TABLE IF NOT EXISTS `card_quality`
(
    `card_quality_id` bigint       NOT NULL AUTO_INCREMENT,
    `abbreviation`    varchar(255) NOT NULL,
    `name`            varchar(255) NOT NULL,
    PRIMARY KEY (`card_quality_id`),
    UNIQUE KEY `UK_ffeaegm3wpjmdv27hl70tdxg2` (`abbreviation`),
    UNIQUE KEY `UK_8lfibsl90cus7fdyjr905191f` (`name`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;

-- Table `card_rarity`
CREATE TABLE IF NOT EXISTS `card_rarity`
(
    `card_rarity_id` bigint       NOT NULL AUTO_INCREMENT,
    `name`           varchar(255) NOT NULL,
    PRIMARY KEY (`card_rarity_id`),
    UNIQUE KEY `UK_lfbtrn21leny9afgkteubfly1` (`name`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;

-- Table `card_set`
CREATE TABLE IF NOT EXISTS `card_set`
(
    `card_set_id` bigint NOT NULL AUTO_INCREMENT,
    `code`        varchar(255) DEFAULT NULL,
    `name`        varchar(255) DEFAULT NULL,
    PRIMARY KEY (`card_set_id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;

-- Table `card_type`
CREATE TABLE IF NOT EXISTS `card_type`
(
    `card_type_id` bigint NOT NULL AUTO_INCREMENT,
    `name`         varchar(255) DEFAULT NULL,
    PRIMARY KEY (`card_type_id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;

-- Table `media`
CREATE TABLE IF NOT EXISTS `media`
(
    `file_id`   bigint       NOT NULL AUTO_INCREMENT,
    `file_name` varchar(255) NOT NULL,
    PRIMARY KEY (`file_id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;

-- Table `role`
CREATE TABLE IF NOT EXISTS `role`
(
    `role_id` bigint                NOT NULL AUTO_INCREMENT,
    `type`    enum ('USER','ADMIN') NOT NULL,
    PRIMARY KEY (`role_id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;

-- Table `user`
CREATE TABLE IF NOT EXISTS `user`
(
    `user_id`              bigint       NOT NULL AUTO_INCREMENT,
    `city`                 varchar(255) NOT NULL,
    `creation_date`        datetime(6)  NOT NULL,
    `department`           int          NOT NULL,
    `email`                varchar(255) NOT NULL,
    `is_active`            bit(1)       NOT NULL,
    `is_banned`            bit(1)       NOT NULL,
    `last_connection_date` datetime(6)  NOT NULL,
    `password`             varchar(255) NOT NULL,
    `user_name`            varchar(255) NOT NULL,
    `file_id`              bigint DEFAULT NULL,
    `role_id`              bigint DEFAULT NULL,
    PRIMARY KEY (`user_id`),
    UNIQUE KEY `UK_ob8kqyqqgmefl0aco34akdtpe` (`email`),
    UNIQUE KEY `UK_lqjrcobrh9jc8wpcar64q1bfh` (`user_name`),
    KEY `FKltyroa17bwbeuq15hhjbx1y1f` (`file_id`),
    KEY `FKdl9dqp078pc03g6kdnxmnlqpc` (`role_id`),
    CONSTRAINT `FKdl9dqp078pc03g6kdnxmnlqpc` FOREIGN KEY (`role_id`) REFERENCES `role` (`role_id`),
    CONSTRAINT `FKltyroa17bwbeuq15hhjbx1y1f` FOREIGN KEY (`file_id`) REFERENCES `media` (`file_id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;

-- Table `user_card`
CREATE TABLE IF NOT EXISTS `user_card`
(
    `user_card_id` bigint NOT NULL AUTO_INCREMENT,
    `is_active`    bit(1) DEFAULT NULL,
    `card_id`      bigint NOT NULL,
    `language_id`  bigint NOT NULL,
    `quality_id`   bigint NOT NULL,
    `user_id`      bigint NOT NULL,
    PRIMARY KEY (`user_card_id`),
    KEY `FK441bl0wnj3hxcj8c18lyxw9e1` (`card_id`),
    KEY `FKqsehjwfyoe89up0qfiv0n1fid` (`language_id`),
    KEY `FKcwpqw1j6rexyy3gxoeh70bmyw` (`quality_id`),
    KEY `FKch5b97hgn80v2enq2r22gjneo` (`user_id`),
    CONSTRAINT `FK441bl0wnj3hxcj8c18lyxw9e1` FOREIGN KEY (`card_id`) REFERENCES `card` (`card_id`),
    CONSTRAINT `FKch5b97hgn80v2enq2r22gjneo` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`),
    CONSTRAINT `FKcwpqw1j6rexyy3gxoeh70bmyw` FOREIGN KEY (`quality_id`) REFERENCES `card_quality` (`card_quality_id`),
    CONSTRAINT `FKqsehjwfyoe89up0qfiv0n1fid` FOREIGN KEY (`language_id`) REFERENCES `card_language` (`card_language_id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;

-- Table `offer`
CREATE TABLE IF NOT EXISTS `offer`
(
    `offer_id`               bigint       NOT NULL AUTO_INCREMENT,
    `accepted_date`          datetime(6) DEFAULT NULL,
    `created_date`           datetime(6)  NOT NULL,
    `status`                 varchar(255) NOT NULL,
    `user_id`                bigint       NOT NULL,
    `wanted_user_card_id`    bigint       NOT NULL,
    `last_modification_date` datetime(6) DEFAULT NULL,
    PRIMARY KEY (`offer_id`),
    KEY `FK141e7qolfthv18c8w7e9dniq2` (`user_id`),
    KEY `FKbt872on33f1irkyuc8m9ffo1a` (`wanted_user_card_id`),
    CONSTRAINT `FK141e7qolfthv18c8w7e9dniq2` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`),
    CONSTRAINT `FKbt872on33f1irkyuc8m9ffo1a` FOREIGN KEY (`wanted_user_card_id`) REFERENCES `user_card` (`user_card_id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;

-- Table `offer_user_card`
CREATE TABLE IF NOT EXISTS `offer_user_card`
(
    `offer_id`     bigint NOT NULL,
    `user_card_id` bigint NOT NULL,
    KEY `FK6yoqq0h0nml3vh0ggdb2tc1ip` (`user_card_id`),
    KEY `FK1uwtl7bgymfvw4onk2flmmewb` (`offer_id`),
    CONSTRAINT `FK1uwtl7bgymfvw4onk2flmmewb` FOREIGN KEY (`offer_id`) REFERENCES `offer` (`offer_id`),
    CONSTRAINT `FK6yoqq0h0nml3vh0ggdb2tc1ip` FOREIGN KEY (`user_card_id`) REFERENCES `user_card` (`user_card_id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;

-- Table `password_token`
CREATE TABLE IF NOT EXISTS `password_token`
(
    `id`                 bigint       NOT NULL AUTO_INCREMENT,
    `date_of_expiration` datetime(6)  NOT NULL,
    `is_changed`         bit(1)       NOT NULL,
    `token`              varchar(255) NOT NULL,
    `user_id`            bigint       NOT NULL,
    PRIMARY KEY (`id`),
    KEY `FKa4awqddrnlvuk5bp7get0vga7` (`user_id`),
    CONSTRAINT `FKa4awqddrnlvuk5bp7get0vga7` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;

-- Insertions into `card_quality`
INSERT INTO card_quality (name, abbreviation)
VALUES ('Mint', 'M'),
       ('Near Mint', 'NM'),
       ('Excellent', 'EX'),
       ('Good', 'GD'),
       ('Light Played', 'LP'),
       ('Played', 'PL'),
       ('Poor', 'P');

-- Insertions into `card_rarity`
INSERT INTO card_rarity (name)
VALUES ('Common'),
       ('Uncommon'),
       ('Rare'),
       ('Mythic'),
       ('Basic Land'),
       ('Special');

-- Insertions into `card_language`
INSERT INTO card_language (name)
VALUES ('English'),
       ('French');

-- Insertions into `role`
INSERT INTO role (type)
VALUES ('USER'),
       ('ADMIN');

-- Insertions into `card_set`
INSERT INTO card_set (card_set_id, code, name)
VALUES (1, '10E', 'Tenth Edition'),
       (2, '2ED', 'Unlimited Edition'),
       (3, '2X2', 'Double Masters 2022'),
       (4, '2XM', 'Double Masters'),
       (5, '30A', '30th Anniversary Edition'),
       (6, '3ED', 'Revised Edition'),
       (7, '40K', 'Warhammer 40,000 Commander'),
       (8, '4BB', 'Fourth Edition Foreign Black Border'),
       (9, '4ED', 'Fourth Edition'),
       (10, '5DN', 'Fifth Dawn'),
       (11, '5ED', 'Fifth Edition'),
       (12, '6ED', 'Classic Sixth Edition'),
       (13, '7ED', 'Seventh Edition'),
       (14, '8ED', 'Eighth Edition'),
       (15, '9ED', 'Ninth Edition'),
       (16, 'A25', 'Masters 25'),
       (17, 'AAFR', 'Adventures in the Forgotten Realms Art Series'),
       (18, 'ABRO', 'The Brothers\' War Art Series'),
       (19, 'ACLB', 'Battle for Baldur\'s Gate Art Series'),
       (20, 'ACMM', 'Commander Masters Art Series'),
       (21, 'ACR', 'Assassin\'s Creed'),
       (22, 'ADMU', 'Dominaria United Art Series'),
       (23, 'AER', 'Aether Revolt'),
       (24, 'AFC', 'Forgotten Realms Commander'),
       (25, 'AFR', 'Adventures in the Forgotten Realms'),
       (26, 'AJMP', 'Jumpstart Arena Exclusives'),
       (27, 'AKH', 'Amonkhet'),
       (28, 'AKHM', 'Kaldheim Art Series'),
       (29, 'AKR', 'Amonkhet Remastered'),
       (30, 'ALA', 'Shards of Alara'),
       (31, 'ALCI', 'The Lost Caverns of Ixalan Art Series'),
       (32, 'ALL', 'Alliances'),
       (33, 'ALTR', 'Tales of Middle-earth Art Series'),
       (34, 'AMH1', 'Modern Horizons Art Series'),
       (35, 'AMH2', 'Modern Horizons 2 Art Series'),
       (36, 'AMID', 'Midnight Hunt Art Series'),
       (37, 'AMKM', 'Murders at Karlov Manor Art Series'),
       (38, 'AMOM', 'March of the Machine Art Series'),
       (39, 'ANA', 'Arena New Player Experience'),
       (40, 'ANB', 'Arena Beginner Set'),
       (41, 'ANEO', 'Neon Dynasty Art Series'),
       (42, 'AONE', 'Phyrexia: All Will Be One Art Series'),
       (43, 'AOTJ', 'Outlaws of Thunder Junction Art Series'),
       (44, 'APC', 'Apocalypse'),
       (45, 'ARB', 'Alara Reborn'),
       (46, 'ARC', 'Archenemy'),
       (47, 'ARN', 'Arabian Nights'),
       (48, 'ASNC', 'New Capenna Art Series'),
       (49, 'ASTX', 'Strixhaven Art Series'),
       (50, 'ATH', 'Anthologies'),
       (51, 'ATQ', 'Antiquities'),
       (52, 'AVOW', 'Crimson Vow Art Series'),
       (53, 'AVR', 'Avacyn Restored'),
       (54, 'AWOE', 'Wilds of Eldraine Art Series'),
       (55, 'AZNR', 'Zendikar Rising Art Series'),
       (56, 'BBD', 'Battlebond'),
       (57, 'BCHR', 'Chronicles Foreign Black Border'),
       (58, 'BFZ', 'Battle for Zendikar'),
       (59, 'BIG', 'The Big Score'),
       (60, 'BLB', 'Bloomburrow'),
       (61, 'BNG', 'Born of the Gods'),
       (62, 'BOK', 'Betrayers of Kamigawa'),
       (63, 'BOT', 'Transformers'),
       (64, 'BRB', 'Battle Royale Box Set'),
       (65, 'BRC', 'The Brothers\' War Commander'),
       (66, 'BRO', 'The Brothers\' War'),
       (67, 'BRR', 'The Brothers\' War Retro Artifacts'),
       (68, 'BTD', 'Beatdown Box Set'),
       (69, 'C13', 'Commander 2013'),
       (70, 'C14', 'Commander 2014'),
       (71, 'C15', 'Commander 2015'),
       (72, 'C16', 'Commander 2016'),
       (73, 'C17', 'Commander 2017'),
       (74, 'C18', 'Commander 2018'),
       (75, 'C19', 'Commander 2019'),
       (76, 'C20', 'Commander 2020'),
       (77, 'C21', 'Commander 2021'),
       (78, 'CC1', 'Commander Collection: Green'),
       (79, 'CC2', 'Commander Collection: Black'),
       (80, 'CED', 'Collectors\' Edition'),
       (81, 'CEI', 'Intl. Collectors\' Edition'),
       (82, 'CHK', 'Champions of Kamigawa'),
       (83, 'DGM', 'Dragon\'s Maze'),
       (84, 'CHR', 'Chronicles'),
       (85, 'CLB', 'Commander Legends: Battle for Baldur\'s Gate'),
       (86, 'CLU', 'Ravnica: Clue Edition'),
       (87, 'CM1', 'Commander\'s Arsenal'),
       (88, 'CM2', 'Commander Anthology Volume II'),
       (89, 'CMA', 'Commander Anthology'),
       (90, 'CMB1', 'Mystery Booster Playtest Cards 2019'),
       (91, 'CMB2', 'Mystery Booster Playtest Cards 2021'),
       (92, 'CMD', 'Commander 2011'),
       (93, 'CMM', 'Commander Masters'),
       (94, 'CMR', 'Commander Legends'),
       (95, 'CN2', 'Conspiracy: Take the Crown'),
       (96, 'CNS', 'Conspiracy'),
       (97, 'CON', 'Conflux'),
       (98, 'CP1', 'Magic 2015 Clash Pack'),
       (99, 'CP2', 'Fate Reforged Clash Pack'),
       (100, 'CP3', 'Magic Origins Clash Pack'),
       (101, 'CSP', 'Coldsnap'),
       (102, 'CST', 'Coldsnap Theme Decks'),
       (103, 'DA1', 'Unknown Event'),
       (104, 'DBL', 'Innistrad: Double Feature'),
       (105, 'DD1', 'Duel Decks: Elves vs. Goblins'),
       (106, 'DD2', 'Duel Decks: Jace vs. Chandra'),
       (107, 'DD3', 'Duel Decks: Anthology'),
       (108, 'DDC', 'Duel Decks: Divine vs. Demonic'),
       (109, 'DDD', 'Duel Decks: Garruk vs. Liliana'),
       (110, 'DDE', 'Duel Decks: Phyrexia vs. the Coalition'),
       (111, 'DDF', 'Duel Decks: Elspeth vs. Tezzeret'),
       (112, 'DDG', 'Duel Decks: Knights vs. Dragons'),
       (113, 'DDH', 'Duel Decks: Ajani vs. Nicol Bolas'),
       (114, 'DDI', 'Duel Decks: Venser vs. Koth'),
       (115, 'DDJ', 'Duel Decks: Izzet vs. Golgari'),
       (116, 'DDK', 'Duel Decks: Sorin vs. Tibalt'),
       (117, 'DDL', 'Duel Decks: Heroes vs. Monsters'),
       (118, 'DDM', 'Duel Decks: Jace vs. Vraska'),
       (119, 'DDN', 'Duel Decks: Speed vs. Cunning'),
       (120, 'DDO', 'Duel Decks: Elspeth vs. Kiora'),
       (121, 'DDP', 'Duel Decks: Zendikar vs. Eldrazi'),
       (122, 'DDQ', 'Duel Decks: Blessed vs. Cursed'),
       (123, 'DDR', 'Duel Decks: Nissa vs. Ob Nixilis'),
       (124, 'DDS', 'Duel Decks: Mind vs. Might'),
       (125, 'DDT', 'Duel Decks: Merfolk vs. Goblins'),
       (126, 'DDU', 'Duel Decks: Elves vs. Inventors'),
       (127, 'DIS', 'Dissension'),
       (128, 'DKA', 'Dark Ascension'),
       (129, 'DKM', 'Deckmasters'),
       (130, 'DMC', 'Dominaria United Commander'),
       (131, 'DMR', 'Dominaria Remastered'),
       (132, 'DMU', 'Dominaria United'),
       (133, 'DOM', 'Dominaria'),
       (134, 'DPA', 'Duels of the Planeswalkers'),
       (135, 'DRB', 'From the Vault: Dragons'),
       (136, 'DRK', 'The Dark'),
       (137, 'DST', 'Darksteel'),
       (138, 'DTK', 'Dragons of Tarkir'),
       (139, 'DVD', 'Duel Decks Anthology: Divine vs. Demonic'),
       (140, 'E01', 'Archenemy: Nicol Bolas'),
       (141, 'E02', 'Explorers of Ixalan'),
       (142, 'EA1', 'Explorer Anthology 1'),
       (143, 'EA2', 'Explorer Anthology 2'),
       (144, 'EA3', 'Explorer Anthology 3'),
       (145, 'ELD', 'Throne of Eldraine'),
       (146, 'EMA', 'Eternal Masters'),
       (147, 'EMN', 'Eldritch Moon'),
       (148, 'EVE', 'Eventide'),
       (149, 'EVG', 'Duel Decks Anthology: Elves vs. Goblins'),
       (150, 'EXO', 'Exodus'),
       (151, 'EXP', 'Zendikar Expeditions'),
       (152, 'F01', 'Friday Night Magic 2001'),
       (153, 'F02', 'Friday Night Magic 2002'),
       (154, 'F03', 'Friday Night Magic 2003'),
       (155, 'F04', 'Friday Night Magic 2004'),
       (156, 'F05', 'Friday Night Magic 2005'),
       (157, 'F06', 'Friday Night Magic 2006'),
       (158, 'F07', 'Friday Night Magic 2007'),
       (159, 'F08', 'Friday Night Magic 2008'),
       (160, 'F09', 'Friday Night Magic 2009'),
       (161, 'F10', 'Friday Night Magic 2010'),
       (162, 'F11', 'Friday Night Magic 2011'),
       (163, 'F12', 'Friday Night Magic 2012'),
       (164, 'F13', 'Friday Night Magic 2013'),
       (165, 'F14', 'Friday Night Magic 2014'),
       (166, 'F15', 'Friday Night Magic 2015'),
       (167, 'F16', 'Friday Night Magic 2016'),
       (168, 'F17', 'Friday Night Magic 2017'),
       (169, 'F18', 'Friday Night Magic 2018'),
       (170, 'FBB', 'Foreign Black Border'),
       (171, 'FBRO', 'The Brothers\' War Jumpstart Front Cards'),
       (172, 'FCLU', 'Ravnica: Clue Edition Front Cards'),
       (173, 'FDMU', 'Dominaria United Jumpstart Front Cards'),
       (174, 'FEM', 'Fallen Empires'),
       (175, 'FJ22', 'Jumpstart 2022 Front Cards'),
       (176, 'FJMP', 'Jumpstart Front Cards'),
       (177, 'FLTR', 'Tales of Middle-earth Front Cards'),
       (178, 'FMB1', 'Mystery Booster Retail Edition Foils'),
       (179, 'FMOM', 'March of the Machine Jumpstart Front Cards'),
       (180, 'FNM', 'Friday Night Magic 2000'),
       (181, 'FONE', 'Phyrexia: All Will Be One Jumpstart Front Cards'),
       (182, 'FRF', 'Fate Reforged'),
       (183, 'FUT', 'Future Sight'),
       (184, 'G00', 'Judge Gift Cards 2000'),
       (185, 'G01', 'Judge Gift Cards 2001'),
       (186, 'G02', 'Judge Gift Cards 2002'),
       (187, 'G03', 'Judge Gift Cards 2003'),
       (188, 'G04', 'Judge Gift Cards 2004'),
       (189, 'G05', 'Judge Gift Cards 2005'),
       (190, 'G06', 'Judge Gift Cards 2006'),
       (191, 'G07', 'Judge Gift Cards 2007'),
       (192, 'G08', 'Judge Gift Cards 2008'),
       (193, 'G09', 'Judge Gift Cards 2009'),
       (194, 'G10', 'Judge Gift Cards 2010'),
       (195, 'G11', 'Judge Gift Cards 2011'),
       (196, 'G17', '2017 Gift Pack'),
       (197, 'G18', 'M19 Gift Pack'),
       (198, 'G99', 'Judge Gift Cards 1999'),
       (199, 'GDY', 'Game Day Promos'),
       (200, 'GK1', 'GRN Guild Kit'),
       (201, 'GK2', 'RNA Guild Kit'),
       (202, 'GN2', 'Game Night 2019'),
       (203, 'GN3', 'Game Night: Free-for-All'),
       (204, 'GNT', 'Game Night'),
       (205, 'GPT', 'Guildpact'),
       (206, 'GRN', 'Guilds of Ravnica'),
       (207, 'GS1', 'Global Series Jiang Yanggu & Mu Yanling'),
       (208, 'GTC', 'Gatecrash'),
       (209, 'GVL', 'Duel Decks Anthology: Garruk vs. Liliana'),
       (210, 'H09', 'Premium Deck Series: Slivers'),
       (211, 'H17', 'HasCon 2017'),
       (212, 'H1R', 'Modern Horizons 1 Timeshifts'),
       (213, 'HA1', 'Historic Anthology 1'),
       (214, 'HA2', 'Historic Anthology 2'),
       (215, 'HA3', 'Historic Anthology 3'),
       (216, 'HA4', 'Historic Anthology 4'),
       (217, 'HA5', 'Historic Anthology 5'),
       (218, 'HA6', 'Historic Anthology 6'),
       (219, 'HA7', 'Historic Anthology 7'),
       (220, 'HBG', 'Alchemy Horizons: Baldur\'s Gate'),
       (221, 'HHO', 'Happy Holidays'),
       (222, 'HML', 'Homelands'),
       (223, 'HOP', 'Planechase'),
       (224, 'HOU', 'Hour of Devastation'),
       (225, 'HTR16', '2016 Heroes of the Realm'),
       (226, 'HTR17', '2017 Heroes of the Realm'),
       (227, 'HTR18', '2018 Heroes of the Realm'),
       (228, 'HTR19', '2019 Heroes of the Realm'),
       (229, 'HTR20', '2020 Heroes of the Realm'),
       (230, 'ICE', 'Ice Age'),
       (231, 'IKO', 'Ikoria: Lair of Behemoths'),
       (232, 'IMA', 'Iconic Masters'),
       (233, 'INV', 'Invasion'),
       (234, 'ISD', 'Innistrad'),
       (235, 'ITP', 'Introductory Two-Player Set'),
       (236, 'J12', 'Judge Gift Cards 2012'),
       (237, 'J13', 'Judge Gift Cards 2013'),
       (238, 'J14', 'Judge Gift Cards 2014'),
       (239, 'J15', 'Judge Gift Cards 2015'),
       (240, 'J16', 'Judge Gift Cards 2016'),
       (241, 'J17', 'Judge Gift Cards 2017'),
       (242, 'J18', 'Judge Gift Cards 2018'),
       (243, 'J19', 'Judge Gift Cards 2019'),
       (244, 'J20', 'Judge Gift Cards 2020'),
       (245, 'J21', 'Jumpstart: Historic Horizons'),
       (246, 'J22', 'Jumpstart 2022'),
       (247, 'JGP', 'Judge Gift Cards 1998'),
       (248, 'JMP', 'Jumpstart'),
       (249, 'JOU', 'Journey into Nyx'),
       (250, 'JUD', 'Judgment'),
       (251, 'JVC', 'Duel Decks Anthology: Jace vs. Chandra'),
       (252, 'KHC', 'Kaldheim Commander'),
       (253, 'KHM', 'Kaldheim'),
       (254, 'KLD', 'Kaladesh'),
       (255, 'KLR', 'Kaladesh Remastered'),
       (256, 'KTK', 'Khans of Tarkir'),
       (257, 'L12', 'League Tokens 2012'),
       (258, 'L13', 'League Tokens 2013'),
       (259, 'L14', 'League Tokens 2014'),
       (260, 'L15', 'League Tokens 2015'),
       (261, 'L16', 'League Tokens 2016'),
       (262, 'L17', 'League Tokens 2017'),
       (263, 'LCC', 'The Lost Caverns of Ixalan Commander'),
       (264, 'LCI', 'The Lost Caverns of Ixalan'),
       (265, 'LEA', 'Limited Edition Alpha'),
       (266, 'LEB', 'Limited Edition Beta'),
       (267, 'LEG', 'Legends'),
       (268, 'LGN', 'Legions'),
       (269, 'LRW', 'Lorwyn'),
       (270, 'LTC', 'Tales of Middle-earth Commander'),
       (271, 'LTR', 'The Lord of the Rings: Tales of Middle-earth'),
       (272, 'M10', 'Magic 2010'),
       (273, 'M11', 'Magic 2011'),
       (274, 'M12', 'Magic 2012'),
       (275, 'M13', 'Magic 2013'),
       (276, 'M14', 'Magic 2014'),
       (277, 'M15', 'Magic 2015'),
       (278, 'M19', 'Core Set 2019'),
       (279, 'M20', 'Core Set 2020'),
       (280, 'M21', 'Core Set 2021'),
       (281, 'M3C', 'Modern Horizons 3 Commander'),
       (282, 'MAFR', 'Adventures in the Forgotten Realms Minigames'),
       (283, 'MAT', 'March of the Machine: The Aftermath'),
       (284, 'MB1', 'Mystery Booster'),
       (285, 'MBRO', 'The Brothers\' War Minigames'),
       (286, 'MBS', 'Mirrodin Besieged'),
       (287, 'MCLB', 'Commander Legends: Battle for Baldur\'s Gate Minigames'),
       (288, 'MD1', 'Modern Event Deck 2014'),
       (289, 'MDMU', 'Dominaria United Minigames'),
       (290, 'ME1', 'Masters Edition'),
       (291, 'ME2', 'Masters Edition II'),
       (292, 'ME3', 'Masters Edition III'),
       (293, 'ME4', 'Masters Edition IV'),
       (294, 'MED', 'Mythic Edition'),
       (295, 'MGB', 'Multiverse Gift Box'),
       (296, 'MH1', 'Modern Horizons'),
       (297, 'MH2', 'Modern Horizons 2'),
       (298, 'MH3', 'Modern Horizons 3'),
       (299, 'MIC', 'Midnight Hunt Commander'),
       (300, 'MID', 'Innistrad: Midnight Hunt'),
       (301, 'MIR', 'Mirage'),
       (302, 'MKC', 'Murders at Karlov Manor Commander'),
       (303, 'MKHM', 'Kaldheim Minigames'),
       (304, 'MKM', 'Murders at Karlov Manor'),
       (305, 'MM2', 'Modern Masters 2015'),
       (306, 'MM3', 'Modern Masters 2017'),
       (307, 'MMA', 'Modern Masters'),
       (308, 'MMH2', 'Modern Horizons 2 Minigames'),
       (309, 'MMID', 'Innistrad: Midnight Hunt Minigames'),
       (310, 'MMQ', 'Mercadian Masques'),
       (311, 'MNEO', 'Kamigawa: Neon Dynasty Minigames'),
       (312, 'MOC', 'March of the Machine Commander'),
       (313, 'MOM', 'March of the Machine'),
       (314, 'MONE', 'Phyrexia: All Will Be One Minigames'),
       (315, 'MOR', 'Morningtide'),
       (316, 'MP2', 'Amonkhet Invocations'),
       (317, 'MPR', 'Magic Player Rewards 2001'),
       (318, 'MPS', 'Kaladesh Inventions'),
       (319, 'MRD', 'Mirrodin'),
       (320, 'MSNC', 'Streets of New Capenna Minigames'),
       (321, 'MSTX', 'Strixhaven: School of Mages Minigames'),
       (322, 'MUL', 'Multiverse Legends'),
       (323, 'MVOW', 'Innistrad: Crimson Vow Minigames'),
       (324, 'MZNR', 'Zendikar Rising Minigames'),
       (325, 'NCC', 'New Capenna Commander'),
       (326, 'NEC', 'Neon Dynasty Commander'),
       (327, 'NEM', 'Nemesis'),
       (328, 'NEO', 'Kamigawa: Neon Dynasty'),
       (329, 'NPH', 'New Phyrexia'),
       (330, 'O90P', 'Oversized 90\'s Promos'),
       (331, 'OAFC', 'Forgotten Realms Commander Display Commanders'),
       (332, 'OANA', 'Arena New Player Experience Cards'),
       (333, 'OARC', 'Archenemy Schemes'),
       (334, 'OC13', 'Commander 2013 Oversized'),
       (335, 'OC14', 'Commander 2014 Oversized'),
       (336, 'OC15', 'Commander 2015 Oversized'),
       (337, 'OC16', 'Commander 2016 Oversized'),
       (338, 'OC17', 'Commander 2017 Oversized'),
       (339, 'OC18', 'Commander 2018 Oversized'),
       (340, 'OC19', 'Commander 2019 Oversized'),
       (341, 'OC20', 'Commander 2020 Oversized'),
       (342, 'OC21', 'Commander 2021 Display Commanders'),
       (343, 'OCM1', 'Commander\'s Arsenal Oversized'),
       (344, 'OCMD', 'Commander 2011 Oversized'),
       (345, 'ODY', 'Odyssey'),
       (346, 'OE01', 'Archenemy: Nicol Bolas Schemes'),
       (347, 'OGW', 'Oath of the Gatewatch'),
       (348, 'OHOP', 'Planechase Planes'),
       (349, 'OLEP', 'Oversized League Prizes'),
       (350, 'OLGC', 'Legacy Championship'),
       (351, 'OMIC', 'Midnight Hunt Commander Display Commanders'),
       (352, 'ONC', 'Phyrexia: All Will Be One Commander'),
       (353, 'ONE', 'Phyrexia: All Will Be One'),
       (354, 'ONS', 'Onslaught'),
       (355, 'OPC2', 'Planechase 2012 Planes'),
       (356, 'OPCA', 'Planechase Anthology Planes'),
       (357, 'ORI', 'Magic Origins'),
       (358, 'OTC', 'Outlaws of Thunder Junction Commander'),
       (359, 'OTJ', 'Outlaws of Thunder Junction'),
       (360, 'OTP', 'Breaking News'),
       (361, 'OVNT', 'Vintage Championship'),
       (362, 'OVOC', 'Crimson Vow Commander Display Commanders'),
       (363, 'P02', 'Portal Second Age'),
       (364, 'P03', 'Magic Player Rewards 2003'),
       (365, 'P04', 'Magic Player Rewards 2004'),
       (366, 'P05', 'Magic Player Rewards 2005'),
       (367, 'P06', 'Magic Player Rewards 2006'),
       (368, 'P07', 'Magic Player Rewards 2007'),
       (369, 'P08', 'Magic Player Rewards 2008'),
       (370, 'P09', 'Magic Player Rewards 2009'),
       (371, 'P10', 'Magic Player Rewards 2010'),
       (372, 'P10E', 'Tenth Edition Promos'),
       (373, 'P11', 'Magic Player Rewards 2011'),
       (374, 'P15A', '15th Anniversary Cards'),
       (375, 'P22', 'Judge Gift Cards 2022'),
       (376, 'P23', 'Judge Gift Cards 2023'),
       (377, 'P2HG', 'Two-Headed Giant Tournament'),
       (378, 'P30A', '30th Anniversary Play Promos'),
       (379, 'P30H', '30th Anniversary History Promos'),
       (380, 'P30M', '30th Anniversary Misc Promos'),
       (381, 'P30T', '30th Anniversary Celebration Tokyo'),
       (382, 'P5DN', 'Fifth Dawn Promos'),
       (383, 'P8ED', 'Eighth Edition Promos'),
       (384, 'P9ED', 'Ninth Edition Promos'),
       (385, 'PAER', 'Aether Revolt Promos'),
       (386, 'PAFR', 'Adventures in the Forgotten Realms Promos'),
       (387, 'PAKH', 'Amonkhet Promos'),
       (388, 'PAL00', 'Arena League 2000'),
       (389, 'PAL01', 'Arena League 2001'),
       (390, 'PAL02', 'Arena League 2002'),
       (391, 'PAL03', 'Arena League 2003'),
       (392, 'PAL04', 'Arena League 2004'),
       (393, 'PAL05', 'Arena League 2005'),
       (394, 'PAL06', 'Arena League 2006'),
       (395, 'PAL99', 'Arena League 1999'),
       (396, 'PALA', 'Shards of Alara Promos'),
       (397, 'PALP', 'Asia Pacific Land Program'),
       (398, 'PANA', 'MTG Arena Promos'),
       (399, 'PAPC', 'Apocalypse Promos'),
       (400, 'PARB', 'Alara Reborn Promos'),
       (401, 'PARC', 'Archenemy Promos'),
       (402, 'PARL', 'Arena League 1996'),
       (403, 'PAST', 'Astral Cards'),
       (404, 'PAVR', 'Avacyn Restored Promos'),
       (405, 'PBBD', 'Battlebond Promos'),
       (406, 'PBFZ', 'Battle for Zendikar Promos'),
       (407, 'PBNG', 'Born of the Gods Promos'),
       (408, 'PBOK', 'Betrayers of Kamigawa Promos'),
       (409, 'PBOOK', 'Miscellaneous Book Promos'),
       (410, 'PBRO', 'The Brothers\' War Promos'),
       (411, 'PC2', 'Planechase 2012'),
       (412, 'PCA', 'Planechase Anthology'),
       (413, 'PCBB', 'Cowboy Bebop'),
       (414, 'PCEL', 'Celebration Cards'),
       (415, 'PCHK', 'Champions of Kamigawa Promos'),
       (416, 'PCLB', 'Battle for Baldur\'s Gate Promos'),
       (417, 'PCMD', 'Commander 2011 Launch Party'),
       (418, 'PCMP', 'Champs and States'),
       (419, 'PCMR', 'Commander Legends Promos'),
       (420, 'PCNS', 'Conspiracy Promos'),
       (421, 'PCON', 'Conflux Promos'),
       (422, 'PCSP', 'Coldsnap Promos'),
       (423, 'PCTB', 'From Cute to Brute'),
       (424, 'PCY', 'Prophecy'),
       (425, 'PD2', 'Premium Deck Series: Fire and Lightning'),
       (426, 'PD3', 'Premium Deck Series: Graveborn'),
       (427, 'PDCI', 'DCI Promos'),
       (428, 'PDGM', 'Dragon\'s Maze Promos'),
       (429, 'PDIS', 'Dissension Promos'),
       (430, 'PDKA', 'Dark Ascension Promos'),
       (431, 'PDMU', 'Dominaria United Promos'),
       (432, 'PDOM', 'Dominaria Promos'),
       (433, 'PDP10', 'Duels of the Planeswalkers 2010 Promos'),
       (434, 'PDP12', 'Duels of the Planeswalkers 2012 Promos'),
       (435, 'PDP13', 'Duels of the Planeswalkers 2013 Promos'),
       (436, 'PDP14', 'Duels of the Planeswalkers 2014 Promos'),
       (437, 'PDP15', 'Duels of the Planeswalkers 2015 Promos'),
       (438, 'PDRC', 'Dragon Con'),
       (439, 'PDST', 'Darksteel Promos'),
       (440, 'PDTK', 'Dragons of Tarkir Promos'),
       (441, 'PDTP', 'Duels of the Planeswalkers 2009 Promos'),
       (442, 'PELD', 'Throne of Eldraine Promos'),
       (443, 'PELP', 'European Land Program'),
       (444, 'PEMN', 'Eldritch Moon Promos'),
       (445, 'PEVE', 'Eventide Promos'),
       (446, 'PEWK', 'Eternal Weekend'),
       (447, 'PEXO', 'Exodus Promos'),
       (448, 'PF19', 'MagicFest 2019'),
       (449, 'PF20', 'MagicFest 2020'),
       (450, 'PF21', 'MagicFest 2021'),
       (451, 'PF23', 'MagicFest 2023'),
       (452, 'PF24', 'MagicFest 2024'),
       (453, 'PFRF', 'Fate Reforged Promos'),
       (454, 'PFUT', 'Future Sight Promos'),
       (455, 'PG07', 'Gateway 2007'),
       (456, 'PG08', 'Gateway 2008'),
       (457, 'PGPT', 'Guildpact Promos'),
       (458, 'PGPX', 'Grand Prix Promos'),
       (459, 'PGRN', 'Guilds of Ravnica Promos'),
       (460, 'PGRU', 'Guru'),
       (461, 'PGTC', 'Gatecrash Promos'),
       (462, 'PGTW', 'Gateway 2006'),
       (463, 'PH17', '2017 Heroes of the Realm'),
       (464, 'PH18', '2018 Heroes of the Realm'),
       (465, 'PH19', '2019 Heroes of the Realm'),
       (466, 'PM12', 'Magic 2012 Promos'),
       (467, 'PH20', '2020 Heroes of the Realm'),
       (468, 'PH21', '2021 Heroes of the Realm'),
       (469, 'PH22', '2022 Heroes of the Realm'),
       (470, 'PHED', 'Heads I Win, Tails You Lose'),
       (471, 'PHEL', 'Open the Helvault'),
       (472, 'PHJ', 'Hobby Japan Promos'),
       (473, 'PHOP', 'Planechase Promos'),
       (474, 'PHOU', 'Hour of Devastation Promos'),
       (475, 'PHPR', 'HarperPrism Book Promos'),
       (476, 'PHTR', '2016 Heroes of the Realm'),
       (477, 'PHUK', 'Hachette UK'),
       (478, 'PI13', 'IDW Comics 2013'),
       (479, 'PI14', 'IDW Comics 2014'),
       (480, 'PIDW', 'IDW Comics Inserts'),
       (481, 'PIKO', 'Ikoria: Lair of Behemoths Promos'),
       (482, 'PINV', 'Invasion Promos'),
       (483, 'PIP', 'Fallout'),
       (484, 'PISD', 'Innistrad Promos'),
       (485, 'PJ21', 'Judge Gift Cards 2021'),
       (486, 'PJAS', 'Junior APAC Series'),
       (487, 'PJJT', 'Japan Junior Tournament'),
       (488, 'PJOU', 'Journey into Nyx Promos'),
       (489, 'PJSE', 'Junior Series Europe'),
       (490, 'PJUD', 'Judgment Promos'),
       (491, 'PKHM', 'Kaldheim Promos'),
       (492, 'PKLD', 'Kaladesh Promos'),
       (493, 'PKTK', 'Khans of Tarkir Promos'),
       (494, 'PL21', 'Year of the Ox 2021'),
       (495, 'PL22', 'Year of the Tiger 2022'),
       (496, 'PL23', 'Year of the Rabbit 2023'),
       (497, 'PL24', 'Year of the Dragon 2024'),
       (498, 'PLC', 'Planar Chaos'),
       (499, 'PLCI', 'The Lost Caverns of Ixalan Promos'),
       (500, 'PLG20', 'Love Your LGS 2020'),
       (501, 'PLG21', 'Love Your LGS 2021'),
       (502, 'PLG22', 'Love Your LGS 2022'),
       (503, 'PLGM', 'DCI Legend Membership'),
       (504, 'PLGN', 'Legions Promos'),
       (505, 'PLIST', 'The List'),
       (506, 'PLNY', 'Lunar New Year 2018'),
       (507, 'PLRW', 'Lorwyn Promos'),
       (508, 'PLS', 'Planeshift'),
       (509, 'PLST', 'The List'),
       (510, 'PLTR', 'Tales of Middle-earth Promos'),
       (511, 'PM10', 'Magic 2010 Promos'),
       (512, 'PM11', 'Magic 2011 Promos'),
       (513, 'PM13', 'Magic 2013 Promos'),
       (514, 'PM14', 'Magic 2014 Promos'),
       (515, 'PM15', 'Magic 2015 Promos'),
       (516, 'PM19', 'Core Set 2019 Promos'),
       (517, 'PM20', 'Core Set 2020 Promos'),
       (518, 'PM21', 'Core Set 2021 Promos'),
       (519, 'PMAT', 'March of the Machine: The Aftermath Promos'),
       (520, 'PMBS', 'Mirrodin Besieged Promos'),
       (521, 'PMDA', 'Magic � Duel Masters Promos'),
       (522, 'PMEI', 'Media Inserts'),
       (523, 'PMH1', 'Modern Horizons Promos'),
       (524, 'PMH2', 'Modern Horizons 2 Promos'),
       (525, 'PMIC', 'MicroProse Promos'),
       (526, 'PMID', 'Innistrad: Midnight Hunt Promos'),
       (527, 'PMKM', 'Murders at Karlov Manor Promos'),
       (528, 'PMMQ', 'Mercadian Masques Promos'),
       (529, 'PMOA', 'Magic Online Avatars'),
       (530, 'PMOM', 'March of the Machine Promos'),
       (531, 'PMOR', 'Morningtide Promos'),
       (532, 'PMPS', 'Magic Premiere Shop 2005'),
       (533, 'PMPS06', 'Magic Premiere Shop 2006'),
       (534, 'PMPS07', 'Magic Premiere Shop 2007'),
       (535, 'PMPS08', 'Magic Premiere Shop 2008'),
       (536, 'PMPS09', 'Magic Premiere Shop 2009'),
       (537, 'PMPS10', 'Magic Premiere Shop 2010'),
       (538, 'PMPS11', 'Magic Premiere Shop 2011'),
       (539, 'PMRD', 'Mirrodin Promos'),
       (540, 'PNAT', 'Nationals Promos'),
       (541, 'PNCC', 'New Capenna Commander Promos'),
       (542, 'PNEM', 'Nemesis Promos'),
       (543, 'PNEO', 'Kamigawa: Neon Dynasty Promos'),
       (544, 'PNPH', 'New Phyrexia Promos'),
       (545, 'PODY', 'Odyssey Promos'),
       (546, 'POGW', 'Oath of the Gatewatch Promos'),
       (547, 'PONE', 'Phyrexia: All Will Be One Promos'),
       (548, 'PONS', 'Onslaught Promos'),
       (549, 'POR', 'Portal'),
       (550, 'PORI', 'Magic Origins Promos'),
       (551, 'POTJ', 'Outlaws of Thunder Junction Promos'),
       (552, 'PPC1', 'M15 Prerelease Challenge'),
       (553, 'PPCY', 'Prophecy Promos'),
       (554, 'PPLC', 'Planar Chaos Promos'),
       (555, 'PPLS', 'Planeshift Promos'),
       (556, 'PPP1', 'M20 Promo Packs'),
       (557, 'PPRO', 'Pro Tour Promos'),
       (558, 'PPTK', 'Portal: Three Kingdoms Promos'),
       (559, 'PR2', 'Magic Player Rewards 2002'),
       (560, 'PR23', 'Regional Championship Qualifiers 2023'),
       (561, 'PRAV', 'Ravnica: City of Guilds Promos'),
       (562, 'PRCQ', 'Regional Championship Qualifiers 2022'),
       (563, 'PRED', 'Redemption Program'),
       (564, 'PRES', 'Resale Promos'),
       (565, 'PRIX', 'Rivals of Ixalan Promos'),
       (566, 'PRM', 'Magic Online Promos'),
       (567, 'PRNA', 'Ravnica Allegiance Promos'),
       (568, 'PROE', 'Rise of the Eldrazi Promos'),
       (569, 'PRTR', 'Return to Ravnica Promos'),
       (570, 'PRW2', 'RNA Ravnica Weekend'),
       (571, 'PRWK', 'GRN Ravnica Weekend'),
       (572, 'PS11', 'Salvat 2011'),
       (573, 'PS14', 'San Diego Comic-Con 2014'),
       (574, 'PS15', 'San Diego Comic-Con 2015'),
       (575, 'PS16', 'San Diego Comic-Con 2016'),
       (576, 'PS17', 'San Diego Comic-Con 2017'),
       (577, 'PS18', 'San Diego Comic-Con 2018'),
       (578, 'PS19', 'San Diego Comic-Con 2019'),
       (579, 'PSAL', 'Salvat 2005'),
       (580, 'PSCG', 'Scourge Promos'),
       (581, 'PSDC', 'San Diego Comic-Con 2013'),
       (582, 'PSDG', 'Sega Dreamcast Cards'),
       (583, 'PSHM', 'Shadowmoor Promos'),
       (584, 'PSNC', 'Streets of New Capenna Promos'),
       (585, 'PSOI', 'Shadows over Innistrad Promos'),
       (586, 'PSOK', 'Saviors of Kamigawa Promos'),
       (587, 'PSOM', 'Scars of Mirrodin Promos'),
       (588, 'PSS1', 'BFZ Standard Series'),
       (589, 'PSS2', 'XLN Standard Showdown'),
       (590, 'PSS3', 'M19 Standard Showdown'),
       (591, 'PSS4', 'MKM Standard Showdown'),
       (592, 'PSTH', 'Stronghold Promos'),
       (593, 'PSTX', 'Strixhaven: School of Mages Promos'),
       (594, 'PSUM', 'Summer of Magic'),
       (595, 'PSUS', 'Junior Super Series'),
       (596, 'PSVC', 'Summer Vacation Promos 2022'),
       (597, 'PTBRO', 'The Brothers\' War Southeast Asia Tokens'),
       (598, 'PTC', 'Pro Tour Collector Set'),
       (599, 'PTDMU', 'Dominaria United Southeast Asia Tokens'),
       (600, 'PTG', 'Ponies: The Galloping'),
       (601, 'PTHB', 'Theros Beyond Death Promos'),
       (602, 'PTHS', 'Theros Promos'),
       (603, 'PTK', 'Portal Three Kingdoms'),
       (604, 'PTKDF', 'Tarkir Dragonfury'),
       (605, 'PTMP', 'Tempest Promos'),
       (606, 'PTOR', 'Torment Promos'),
       (607, 'PTSNC', 'Streets of New Capenna Southeast Asia Tokens'),
       (608, 'PTSP', 'Time Spiral Promos'),
       (609, 'PTSR', 'Time Spiral Remastered Promos'),
       (610, 'PUDS', 'Urza\'s Destiny Promos'),
       (611, 'PULG', 'Urza\'s Legacy Promos'),
       (612, 'PUMA', 'Ultimate Box Topper'),
       (613, 'PUNH', 'Unhinged Promos'),
       (614, 'PURL', 'URL/Convention Promos'),
       (615, 'PUSG', 'Urza\'s Saga Promos'),
       (616, 'PUST', 'Unstable Promos'),
       (617, 'PVAN', 'Vanguard Series'),
       (618, 'PVOW', 'Innistrad: Crimson Vow Promos'),
       (619, 'PW09', 'Wizards Play Network 2009'),
       (620, 'PW10', 'Wizards Play Network 2010'),
       (621, 'PW11', 'Wizards Play Network 2011'),
       (622, 'PW12', 'Wizards Play Network 2012'),
       (623, 'PW21', 'Wizards Play Network 2021'),
       (624, 'PW22', 'Wizards Play Network 2022'),
       (625, 'PW23', 'Wizards Play Network 2023'),
       (626, 'PW24', 'Wizards Play Network 2024'),
       (627, 'PWAR', 'War of the Spark Promos'),
       (628, 'PWCQ', 'World Magic Cup Qualifiers'),
       (629, 'PWCS', 'Planeswalker Championship Promos'),
       (630, 'PWOE', 'Wilds of Eldraine Promos'),
       (631, 'PWOR', 'World Championship Promos'),
       (632, 'PWOS', 'Wizards of the Coast Online Store'),
       (633, 'PWPN', 'Wizards Play Network 2008'),
       (634, 'PWWK', 'Worldwake Promos'),
       (635, 'PXLN', 'Ixalan Promos'),
       (636, 'PXTC', 'XLN Treasure Chest'),
       (637, 'PZ1', 'Legendary Cube Prize Pack'),
       (638, 'PZ2', 'Treasure Chest'),
       (639, 'PZEN', 'Zendikar Promos'),
       (640, 'PZNR', 'Zendikar Rising Promos'),
       (641, 'Q01', 'Challenger Decks 2018'),
       (642, 'Q02', 'Challenger Decks 2019'),
       (643, 'Q03', 'Challenger Decks 2019 Japan'),
       (644, 'Q04', 'Challenger Decks 2020'),
       (645, 'Q05', 'Challenger Decks 2021'),
       (646, 'Q06', 'Pioneer Challenger Decks 2021'),
       (647, 'Q07', 'Challenger Decks 2022'),
       (648, 'Q08', 'Pioneer Challenger Decks 2022'),
       (649, 'RAV', 'Ravnica: City of Guilds'),
       (650, 'REN', 'Renaissance'),
       (651, 'REX', 'Jurassic World Collection'),
       (652, 'RIN', 'Rinascimento'),
       (653, 'RIX', 'Rivals of Ixalan'),
       (654, 'RNA', 'Ravnica Allegiance'),
       (655, 'ROE', 'Rise of the Eldrazi'),
       (656, 'RQS', 'Rivals Quick Start Set'),
       (657, 'RTR', 'Return to Ravnica'),
       (658, 'RVR', 'Ravnica Remastered'),
       (659, 'S00', 'Starter 2000'),
       (660, 'S99', 'Starter 1999'),
       (661, 'SBRO', 'The Brothers\' War Substitute Cards'),
       (662, 'SCD', 'Starter Commander Decks'),
       (663, 'SCG', 'Scourge'),
       (664, 'SCH', 'Store Championships'),
       (665, 'SHM', 'Shadowmoor'),
       (666, 'SIR', 'Shadows over Innistrad Remastered'),
       (667, 'SIS', 'Shadows of the Past'),
       (668, 'SKHM', 'Kaldheim Substitute Cards'),
       (669, 'SLC', 'Secret Lair 30th Anniversary Countdown Kit'),
       (670, 'SLCI', 'The Lost Caverns of Ixalan Substitute Cards'),
       (671, 'SLD', 'Secret Lair Drop'),
       (672, 'SLP', 'Secret Lair Showdown'),
       (673, 'SLU', 'Secret Lair: Ultimate Edition'),
       (674, 'SLX', 'Universes Within'),
       (675, 'SMID', 'Innistrad: Midnight Hunt Substitute Cards'),
       (676, 'SMOM', 'March of the Machine Substitute Cards'),
       (677, 'SNC', 'Streets of New Capenna'),
       (678, 'SNEO', 'Kamigawa: Neon Dynasty Substitute Cards'),
       (679, 'SOI', 'Shadows over Innistrad'),
       (680, 'SOK', 'Saviors of Kamigawa'),
       (681, 'SOM', 'Scars of Mirrodin'),
       (682, 'SPG', 'Special Guests'),
       (683, 'SS1', 'Signature Spellbook: Jace'),
       (684, 'SS2', 'Signature Spellbook: Gideon'),
       (685, 'SS3', 'Signature Spellbook: Chandra'),
       (686, 'SSTX', 'Strixhaven: School of Mages Substitute Cards'),
       (687, 'STA', 'Strixhaven Mystical Archive'),
       (688, 'STH', 'Stronghold'),
       (689, 'STX', 'Strixhaven: School of Mages'),
       (690, 'SUM', 'Summer Magic / Edgar'),
       (691, 'SUNF', 'Unfinity Sticker Sheets'),
       (692, 'SVOW', 'Innistrad: Crimson Vow Substitute Cards'),
       (693, 'SZNR', 'Zendikar Rising Substitute Cards'),
       (694, 'TBTH', 'Battle the Horde'),
       (695, 'TD0', 'Magic Online Theme Decks'),
       (696, 'TD2', 'Duel Decks: Mirrodin Pure vs. New Phyrexia'),
       (697, 'TDAG', 'Defeat a God'),
       (698, 'TFTH', 'Face the Hydra'),
       (699, 'THB', 'Theros Beyond Death'),
       (700, 'THP1', 'Theros Hero\'s Path'),
       (701, 'THP2', 'Born of the Gods Hero\'s Path'),
       (702, 'THP3', 'Journey into Nyx Hero\'s Path'),
       (703, 'THS', 'Theros'),
       (704, 'TMP', 'Tempest'),
       (705, 'TOR', 'Torment'),
       (706, 'TPR', 'Tempest Remastered'),
       (707, 'TSB', 'Time Spiral Timeshifted'),
       (708, 'TSP', 'Time Spiral'),
       (709, 'TSR', 'Time Spiral Remastered'),
       (710, 'UDS', 'Urza\'s Destiny'),
       (711, 'UGIN', 'Ugin\'s Fate'),
       (712, 'UGL', 'Unglued'),
       (713, 'ULG', 'Urza\'s Legacy'),
       (714, 'ULST', 'The List (Unfinity Foil Edition)'),
       (715, 'UMA', 'Ultimate Masters'),
       (716, 'UND', 'Unsanctioned'),
       (717, 'UNF', 'Unfinity'),
       (718, 'UNH', 'Unhinged'),
       (719, 'UPLIST', 'The List (Unfinity Foil Edition)'),
       (720, 'USG', 'Urza\'s Saga'),
       (721, 'UST', 'Unstable'),
       (722, 'V09', 'From the Vault: Exiled'),
       (723, 'V10', 'From the Vault: Relics'),
       (724, 'V11', 'From the Vault: Legends'),
       (725, 'V12', 'From the Vault: Realms'),
       (726, 'V13', 'From the Vault: Twenty'),
       (727, 'V14', 'From the Vault: Annihilation'),
       (728, 'V15', 'From the Vault: Angels'),
       (729, 'V16', 'From the Vault: Lore'),
       (730, 'V17', 'From the Vault: Transform'),
       (731, 'VIS', 'Visions'),
       (732, 'VMA', 'Vintage Masters'),
       (733, 'VOC', 'Crimson Vow Commander'),
       (734, 'VOW', 'Innistrad: Crimson Vow'),
       (735, 'W16', 'Welcome Deck 2016'),
       (736, 'W17', 'Welcome Deck 2017'),
       (737, 'WAR', 'War of the Spark'),
       (738, 'WC00', 'World Championship Decks 2000'),
       (739, 'WC01', 'World Championship Decks 2001'),
       (740, 'WC02', 'World Championship Decks 2002'),
       (741, 'WC03', 'World Championship Decks 2003'),
       (742, 'WC04', 'World Championship Decks 2004'),
       (743, 'WC97', 'World Championship Decks 1997'),
       (744, 'WC98', 'World Championship Decks 1998'),
       (745, 'WC99', 'World Championship Decks 1999'),
       (746, 'WDMU', 'DMU Japanese Promo Tokens'),
       (747, 'WHO', 'Doctor Who'),
       (748, 'WMC', 'World Magic Cup Qualifiers'),
       (749, 'WMKM', 'MKM Japanese Promo Tokens'),
       (750, 'WMOM', 'MOM Japanese Promo Tokens'),
       (751, 'WOC', 'Wilds of Eldraine Commander'),
       (752, 'WOE', 'Wilds of Eldraine'),
       (753, 'WONE', 'ONE Japanese Promo Tokens'),
       (754, 'WOT', 'Wilds of Eldraine: Enchanting Tales'),
       (755, 'WTH', 'Weatherlight'),
       (756, 'WWK', 'Worldwake'),
       (757, 'WWOE', 'WOE Japanese Promo Tokens'),
       (758, 'XANA', 'Arena New Player Experience Extras'),
       (759, 'XLN', 'Ixalan'),
       (760, 'YBRO', 'Alchemy: The Brothers\' War'),
       (761, 'YDMU', 'Alchemy: Dominaria'),
       (762, 'YLCI', 'Alchemy: Ixalan'),
       (763, 'YMID', 'Alchemy: Innistrad'),
       (764, 'YMKM', 'Alchemy: Murders at Karlov Manor'),
       (765, 'YNEO', 'Alchemy: Kamigawa'),
       (766, 'YONE', 'Alchemy: Phyrexia'),
       (767, 'YOTJ', 'Alchemy: Outlaws of Thunder Junction'),
       (768, 'YSNC', 'Alchemy: New Capenna'),
       (769, 'YWOE', 'Alchemy: Wilds of Eldraine'),
       (770, 'ZEN', 'Zendikar'),
       (771, 'ZNC', 'Zendikar Rising Commander'),
       (772, 'ZNE', 'Zendikar Rising Expeditions'),
       (773, 'ZNR', 'Zendikar Rising');

INSERT INTO card_type (card_type_id, name)
VALUES (1, 'Artifact'),
       (2, 'Battle'),
       (3, 'Conspiracy'),
       (4, 'Creature'),
       (5, 'Dragon'),
       (6, 'Elemental'),
       (7, 'Enchantment'),
       (8, 'Goblin'),
       (9, 'Hero'),
       (10, 'instant'),
       (11, 'Instant'),
       (12, 'Jaguar'),
       (13, 'Kindred'),
       (14, 'Knights'),
       (15, 'Land'),
       (16, 'Legend'),
       (17, 'Phenomenon'),
       (18, 'Plane'),
       (19, 'Planeswalker'),
       (20, 'Scheme'),
       (21, 'Sorcery'),
       (22, 'Stickers'),
       (23, 'Summon'),
       (24, 'Tribal'),
       (25, 'Universewalker'),
       (26, 'Vanguard'),
       (27, 'Wolf');
